- alias: "Xmas Lights ON at sunset"
  id: xmaslightsonsunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.xmas_lights

- alias: "Xmas Lights OFF at sunrise"
  id: xmaslightsoffsunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: '00:45:00'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.xmas_lights