- alias: "Coming Home: Bedroom Fan off"
  id: coming_home_bedroom_fan_off
  trigger:
    platform: state
    entity_id: group.presence
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.bedroom_fan