- alias: "Coming Home: Watch YouTube"
  id: coming_home_watch_youtube
  trigger:
    platform: state
    entity_id: group.presence
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
    - condition: state
      entity_id: remote.harmony_hub
      state: 'off'
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.harmony_hub
        activity: "Watch TV"