- alias: "Coming Home: Watch YouTube"
  id: coming_home_watch_youtube
  trigger:
    platform: state
    entity_id: device_tracker.404e36855fdd
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 0
      seconds: 15
  action:
    - service: remote.turn_on
      data:
        entity_id: remote.harmony_hub
        activity: "Watch YouTube"