#######################################################
#
#     TESTING NEW SENSOR: utility_meter
#
#######################################################


- alias: Bathroom Heater set Utility Meter tariff
  id: bathroom_heater_set_utility_meter_tariff
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '21:00:00'
  action:
    - service: utility_meter.next_tariff
      entity_id: utility_meter.daily_energy
    - service: utility_meter.next_tariff
      entity_id: utility_meter.monthly_energy
    - service: utility_meter.next_tariff
      entity_id: utility_meter.mystrom_daily
    - service: utility_meter.next_tariff
      entity_id: utility_meter.mystrom_monthly