- alias: "Reduce Temperature if Window open"
  id: climate_reduce_temperature_window_open
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroomwindow_state
      from: "off"
      to: "on"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.kitchenwindow_state
      from: "off"
      to: "on"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.livingroomwindow_state
      from: "off"
      to: "on"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.officewindow_state
      from: "off"
      to: "on"
      for:
        seconds: 15
        minutes: 0
        hours: 0
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.thermostat
        away_mode: true

- alias: "Increase Temperature if Window closed"
  id: climate_increase_temperature_window_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroomwindow_state
      from: "on"
      to: "off"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.kitchenwindow_state
      from: "on"
      to: "off"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.livingroomwindow_state
      from: "on"
      to: "off"
      for:
        seconds: 15
        minutes: 0
        hours: 0
    - platform: state
      entity_id: binary_sensor.officewindow_state
      from: "on"
      to: "off"
      for:
        seconds: 15
        minutes: 0
        hours: 0
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.thermostat
        away_mode: false