- alias: Bathroom Water Leak
  id: bathroom_water_leak
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000289b541_water_leak
      from: 'off'
      to: 'on'
  action:
    - service: notify.html5
      data:
        message: "Water Leak detected in bathroom!!!"
        title: "Water Leak!"
        data:
          tag: "water_leak_bathroom"