- platform: group
  name: All Lights
  entities:
    - light.bathroom_ceiling
    - light.bathroom_ceiling_1
    - light.bathroom_ceiling_2
    - light.bedroom
    - light.bedroom_4
    - light.bedroom_corner_left
    - light.bedroom_corner_right
    - light.bedroom_corners
    - light.bedroom_lights
    - light.bedroom_main
    - light.bedroom_nightstand
    - light.bedroom_youtube
    - light.ceiling_panel
    - light.celing_panel_bedroom
    - light.computer_lamp_bulb
    - light.entertainment_area_1
    - light.gaming_lights
    - light.kitchen
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_lights
    - light.living_room_1
    - light.living_room_4
    - light.living_room_ceiling_lamp
    - light.living_room_corner_lamp
    - light.living_room_couch
    - light.living_room_lights
    - light.living_room_normal_lights
    - light.living_room_under_couch
    - light.living_room
    - light.livingroom_plant
    - light.office_ceiling
    - light.outdoor_1
    - light.tv_light_bulb
    - light.tv_lights