- platform: group
  name: TV Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light_bulb
    - light.livingroom_plant

- platform: group
  name: Living Room Normal Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light_bulb
    - light.livingroom_plant
    - light.ceiling_panel
    - light.living_room_corner_lamp

- platform: group
  name: Gaming Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light
    - light.livingroom_plant
    - light.computer_lamp

- platform: group
  name: Living Room Lights
  entities:
    - light.tv_light_bulb
    - light.computer_lamp
    - light.livingroom_plant
    - light.living_room_under_couch
    - light.ceiling_panel
    - light.living_room_corner_lamp