- platform: group
  name: TV Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light
    - light.livingroom_plant

- platform: group
  name: Living Room Normal Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light
    - light.livingroom_plant
    - light.living_room_ceiling_lamp

- platform: group
  name: Gaming Lights
  entities:
    - light.living_room_under_couch
    - light.tv_light
    - light.livingroom_plant
    - light.computer_lamp