# Turn off all lights in the Bedroom when Nightstand Lamp is turned off
- alias: "Bedroom turn off all lights when nightstand lamp is turned off"
  id: bedroom_turn_off_slave_nightstand
  trigger:
    - platform: state
      entity_id: light.bedroom_nightstand
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: all
    - service: fan.turn_off
      data:
        entity_id: fan.livingroom_fan


# Philips Hue Motion Sensor Light off, turn off IKEA light too
# - alias: "Kitchen Motion Sensor Lights ON"
  # id: kitchen_motion_sensor_lights_on
  # trigger:
  #   - platform: state
  #     entity_id: light.kitchen_1
  #     from: 'on'
  #     to: 'off'
  # condition:
  #   - condition: state
  #     entity_id: input_boolean.kitchen_automatic_lights
  #     state: 'on'
  # action:
  #   - service: light.turn_off
  #     data:
  #       entity_id: light.kitchen_2
  #   - service: input_boolean.turn_off
  #     data:
  #       entity_id: input_boolean.kitchen_automatic_lights