- alias: "Oversleeping"
  id: bedroom_oversleeping
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: group.presence
      state: 'home'
    - condition: state
      entity_id: input_boolean.holidays
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: binary_sensor.bedroomdoor_state
      state: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 5000
        brightness: 255
    - service: notify.html5
      data:
        message: "YOU ARE OVERSLEEPING!!!"
        title: "Alarmclock"
        data:
          tag: "alarmclock"
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 07:45 am!'
    - delay: 0:05:00
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 07:50 am!'
    - delay: 0:05:00
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 07:55 am!'
    - delay: 0:05:00
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 08:00 am!'
    - delay: 0:05:00
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 08:05 am!'
    - delay: 0:05:00
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 08:10 am!'
    - delay: 0:05:00
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 2200