- alias: "Oversleeping"
  id: bedroom_oversleeping
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_sleeping_bayesian
      state: 'on'
    - condition: state
      entity_id: input_boolean.holidays
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 5000
        brightness: 255
    - service: notify.html5
      data:
        message: "YOU ARE OVERSLEEPING!!!"
        title: "Alarmclock"
        data:
          tag: "alarmclock"
    - service: notify.hangouts
      data:
        message: "YOU ARE OVERSLEEPING!!!"
    # - service: media_player.volume_set
    #   entity_id: media_player.bedroom_speaker
    #   data:
    #     volume_level: 1
    # - delay: 0:00:15
    # - service: media_player.play_media
    #   data:
    #     entity_id: media_player.bedroom_speaker
    #     media_content_type: audio/mp3
    #   data_template:
    #     media_content_id: >
    #       {{ ["https://steff999.duckdns.org/local/audio/alarmclock/annoying_sounds_9min.mp3", "https://steff999.duckdns.org/local/audio/alarmclock/rooster_crowing_30min.mp3"] | random}}
    # - delay: 0:30:00
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 2200
    # - service: media_player.volume_set
    #   entity_id: media_player.bedroom_speaker
    #   data:
    #     volume_level: 0.4