- alias: "Oversleeping"
  id: bedroom_oversleeping
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_sleeping
      state: 'on'
    - condition: state
      entity_id: input_boolean.holidays
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 5000
        brightness: 255
    - service: notify.html5
      data:
        message: "YOU ARE OVERSLEEPING!!!"
        title: "Alarmclock"
        data:
          tag: "alarmclock"
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: 1
    - delay: 0:00:15
    - service: tts.google_say
      entity_id: media_player.bedroom_speaker
      data:
        message: 'You are oversleeping! It is 07:45 am!'
    - delay: 0:30:00
    - service: light.turn_on
      entity_id:
        - light.bedroom_nightstand
        - light.bedroom_4
        - light.bedroom_2
      data:
        kelvin: 2200
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data:
        volume_level: 0.4