- alias: Computer turned ON
  id: computer_turned_on
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_power_status
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: group.presence
          state: 'home'
        - condition: state
          entity_id: binary_sensor.is_sleeping_bayesian
          state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.computer_lamp_bulb

- alias: Computer turned OFF
  id: computer_turned_on
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_power_status
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.computer_lamp_bulb