- alias: "Livingroom: Google Home Volume 09:00:00"
  id: livingroom_google_home_volume_090000
  trigger:
    - platform: time
      at: "09:00:00"
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room_home
      data:
        volume_level: 0.5

- alias: "Livingroom: Google Home Volume 22:00:00"
  id: livingroom_google_home_volume_220000
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room_home
      data:
        volume_level: 0.3