- alias: Away Mode
  id: away_mode
  trigger:
    - platform: state
      entity_id: group.presence
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 15
        seconds: 0
  action:
    - service: light.turn_off
      data:
        entity_id:
          - group.all_lights
    # - service: switch.turn_off
    #   data:
    #     entity_id:
    #       - switch.computer_lamp
    #       - switch.bedroom_fan
    - service: media_player.turn_off
      data:
        entity_id:
          - media_player.sony_bravia_tv
    - service: climate.set_away_mode
      data:
        entity_id: climate.netatmo_living_room
        away_mode: true
    - service: climate.set_away_mode
      data:
        entity_id: climate.bathroom
        away_mode: true

- alias: Leave Home Button Floorplan
  id: leave_home_button_floorplan
  trigger:
    - platform: state
      entity_id: input_boolean.start_leave_home_script
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.leaving_home
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.start_leave_home_script