- alias: "Bedroom Cloth Drying"
  id: bedroom_cloth_drying
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_humidity_trend
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.404e36855fdd
      state: 'not_home'
      for:
        minutes: 15
        seconds: 0
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.bedroom_fan