- alias: "Coming Home"
  id: coming_home
  trigger:
    platform: state
    entity_id: device_tracker.404e36855fdd
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 0
      seconds: 15
  action:
    - service: light.turn_on
      data:
        entity_id:
          - group.tv_lights_on
    - service: switch.turn_off
      data:
        entity_id:
          - switch.bedroom_fan
    - service: media_player.turn_on
      data:
        entity_id:
          - media_player.shield
    - delay: 0:00:10
    - service: switch.turn_on
      data:
        entity_id:
          - switch.youtube_open
    - delay: 0:00:05
    - service: switch.turn_off
      data:
        entity_id:
          - switch.youtube_open
    - service: climate.set_away_mode
      data:
        entity_id: climate.thermostat
        away_mode: false
    - service: climate.set_away_mode
      data:
        entity_id: climate.bathroom
        away_mode: false
    - service: switch.turn_off
      data:
        entity_id:
          - switch.bedroom_fan