- alias: "Nobody at Home"
  id: nobody_home
  trigger:
    - platform: time
      minutes: '\5'
      seconds: 00
  condition:
    - condition: state
      entity_id: device_tracker.404e36855fdd
      state: 'not_home'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  action:
    - service: light.turn_off
      data:
        entity_id:
          - group.all_lights