- alias: "Nobody at Home"
  id: nobody_home
  trigger:
    - platform: time_pattern
      minutes: '\5'
  condition:
    - condition: state
      entity_id: group.presence
      state: 'not_home'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  action:
    - service: light.turn_off
      entity_id: all